language: ruby
rvm:
  - 2.7.4
before_install:
  - rvm use 2.7.4 --default && ruby --version
  - gem update 
  - gem install bundler
  - bundle install
script: 
  - bundle exec jekyll build
after_success:
  - git clone https://github.com/HalleyFang/halleyfang.github.io.git
  - cd halleyfang.github.io && rm -rf * && cp -r ../_site/* .
  - git config user.name "Travis CI"
  - git config user.email "fangxu568@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$S_KEY@github.com/HalleyFang/halleyfang.github.io.git gh-pages
env:
  global:
    secure: $S_KEY
