language: ruby
rvm:
  - 2.7.4
before_install:
  - rvm use 2.7.4 --default && ruby --version
  - gem update 
  - gem install bundler
  - bundle install
script: 
  - bundle exec jekyll build
env:
  global:
    secure: $S_KEY
