title: halley.fang 个人博客
site_title: blog
site_url: //halley.github.io/
description: halley.fang 个人博客
paginate: 5
paginate_path: "post-page/page:num"
category_dir: category/
tag_dir: tag/
excerpt_separator: "\n//more\n"

plugins:
  - asciidoctor-diagram
  - jekyll-asciidoc

exclude:
  - LICENSE.adoc
  - README.adoc
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: highlightjs

plugins:
  - asciidoctor-diagram
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  excerpt_doctype: inline
  attributes:
    - idseparator=_
    - source-highlighter=highlightjs
    - icons=font
    - showtitle=@
    - sectnumlevels=5
    - experimental
    - numbered!
    - hardbreaks
    - linkcss
    - stylesdir=css
    - iconfont-remote!
    - webfonts!
    - linkattrs
    - nofooter

github: HalleyFang
email: qingyeliufeng@163.com
qq: 458930591

disqus: HalleyFang
